apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-only-webapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: webapp
  rules:
  - from:
    - source:
        namespaces: ["default"]