groups:
- name: basic-alerts
  rules:
  - alert: PodRestartHigh
    expr: increase(kube_pod_container_status_restarts_total[5m]) > 2
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High restart rate"
      description: "Pod has restarted more than 2 times in the last 5 minutes."

  - alert: HighCPUUsage
    expr: sum(rate(container_cpu_usage_seconds_total[2m])) by (pod) > 0.5
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage"
      description: "Pod CPU usage is over 50% for 2 minutes."
