apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      version: v2
  template:
    metadata:
      labels:
        app: webapp
        version: v2
    spec:
      containers:
      - name: web
        image: hashicorp/http-echo
        args: ["-text=Hello from v2"]
        ports:
        - containerPort: 5678
